# Production deployment configuration for Render
services:
- type: web
  name: marbitz-battlebot
  runtime: python
  repo: https://github.com/ikbenFranco/Marbitz-Battlebot
  plan: starter
  envVars:
  - key: BOT_TOKEN
    value: null  # Set this in Render dashboard
    sync: false
  - key: PYTHON_VERSION
    value: "3.11"
    sync: false
  region: oregon
  buildCommand: pip install -r requirements-prod.txt
  startCommand: python main.py
  autoDeployTrigger: commit
  scaling:
    minInstances: 1
    maxInstances: 1
  healthCheckPath: /health
  shutdownTimeout: 30
version: "1"
